name: Build + Test

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: zip -r MDX.zip MDX -x "*.DS_Store"

      - name: Upload style to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: MDX.zip

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Go
        uses: actions/setup-go@v5

      - name: Install Deps
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v${VALE_VERSION}/vale_${VALE_VERSION}_Linux_64-bit.tar.gz
          mkdir testdata/bin && tar -xvzf vale_${VALE_VERSION}_Linux_64-bit.tar.gz -C testdata/bin
          echo "./testdata/bin" >> $GITHUB_PATH
          ./testdata/bin/vale -v
        env:
          VALE_VERSION: 3.9.1

      - name: Features
        run: |
          zip -r MDX.zip MDX -x "*.DS_Store"
          cd testdata
          ./bin/vale sync
          ./bin/vale transform test.mdx > out.md
          cd -
          go run main.go
